import type { Metadata } from "next";
import CareerApplication from "@/components/CareerApplication";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { siteConfig } from "@/data/site";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";

export const metadata: Metadata = {
  title: "Careers",
  description: "Join Duoph. Explore openings for Digital Marketing Intern, Digital Sales, and Frontend Developer.",
  alternates: { canonical: "/careers" },
  openGraph: { title: "Careers at Duoph", description: "Explore our openings in digital marketing, sales, and frontend development.", url: "/careers" },
};
const openings = [
  { title: "Digital Marketing Intern", team: "Marketing", description: "Help businesses reach the right people through thoughtful content and digital campaigns.", responsibilities: ["Support social media planning and content creation.", "Assist with SEO research and campaign reporting.", "Track results and bring fresh ideas to the team."], skills: "An interest in digital marketing, clear writing, and a willingness to learn." },
  { title: "Digital Sales", team: "Business development", description: "Connect with potential clients and help them find the right digital solutions for their business.", responsibilities: ["Research potential clients and identify new opportunities.", "Introduce our services and understand client needs.", "Follow up on enquiries and maintain clear sales records."], skills: "Strong communication, thoughtful follow-up, and an interest in technology and business." },
  { title: "Frontend Developer", team: "Engineering", description: "Turn thoughtful designs into fast, accessible websites and interfaces that people enjoy using.", responsibilities: ["Build responsive interfaces with HTML, CSS, and JavaScript.", "Collaborate on reusable components and API integrations.", "Test usability, accessibility, and browser compatibility."], skills: "Comfort with HTML, CSS, JavaScript, and React. Share examples of interfaces you’ve built." },
];

export default function Careers() {
  return <div className="studio-site careers-page" id="top"><a className="skip-link" href="#main-content">Skip to content</a><SiteHeader /><main id="main-content">
    <section className="hero shell"><div className="hero-layout"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Careers at Duoph</p><h1>Bring your curiosity.<br /><span>Build with us.</span></h1><div className="hero-bottom"><p>Good work starts with people who care. Join a team that values clear thinking, shared learning, and attention to detail.</p><a className="pill-button" href="#opportunities">View 3 open roles <ArrowDown size={18} /></a></div></div></div><div className="hero-note"><span>Different strengths. One shared direction.</span><span>Design · Technology · Growth</span></div></section>
    <section id="opportunities" className="soft-section section-space"><div className="shell"><p className="eyebrow">01 / Open positions</p><div className="section-top"><h2>Find your next step.</h2><p>Explore the roles below. Tell us about yourself and the work you’d like to do.</p></div><div className="job-list">{openings.map((job, index) => <article className="job-card" key={job.title}><div className="job-intro"><span className="eyebrow">0{index + 1} / {job.team}</span><h3>{job.title}</h3><p>{job.description}</p></div><div className="job-details"><h4>What you’ll work on</h4><ul>{job.responsibilities.map(item => <li key={item}>{item}</li>)}</ul><h4>What you’ll bring</h4><p>{job.skills}</p></div><CareerApplication role={job.title} /></article>)}</div><p className="section-note">Choose “Apply for this role”, enter your details, then send your application using the email popup.</p></div></section>
    <section className="shell section-space two-column"><div><p className="eyebrow">02 / Life at Duoph</p><h2>Room to contribute.<br />Space to grow.</h2></div><div className="values-list"><article><h3>Think beyond the brief</h3><p>Ask questions, share ideas, and connect your work to what people actually need.</p></article><article><h3>Learn by building</h3><p>Work on real business challenges and develop your craft through collaboration and feedback.</p></article><article><h3>Care about the details</h3><p>Make things clear, useful, and reliable. Take pride in the work and the way we get there together.</p></article></div></section>
    <section className="soft-section section-space" id="introduce"><div className="shell two-column"><div><p className="eyebrow">03 / How to apply</p><h2>A little about you.<br />A glimpse of your work.</h2></div><div className="apply-copy"><p>Choose a role above and enter your name, email, phone, and notice period. Submit the form to open a popup, then use “Open email draft” to review and send your application to admin@duoph.in.</p><p>We’ll review your application and get in touch if your experience matches the role. Working arrangements and next steps will be discussed during the hiring process.</p><a className="contact-email" href={`mailto:${siteConfig.email}`}>{siteConfig.email}<ArrowUpRight size={20} /></a><p>Have a question before applying? Email us at the address above.</p></div></div></section>
  </main><SiteFooter /></div>;
}
